import localFont from "next/font/local";
import "./globals.css";
import Header from "./(components)/Header";
import { Providers } from "./Providers";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <div className="flex-grow overflow-y-auto bg-page text-default-text">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}